on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          env_var: ${{ vars.OPENAPI_KEY }}
        with:
          host: "197.248.212.233"
          username: "musa"
          password: "@machmende1994."
          script: |
            cd /media
            git pull
            bun i
            pm2 restart index

# Fix Issue regarding deploying due to bun command
# https://github.com/appleboy/ssh-action/issues/31#issuecomment-1006565847 (Comment out [ -z "$PS1" ] && return` in /etc/bash.bashrc)
